language: node_js
node_js:
  - "8.10.0"
  - "6.10.3"

script:
   - npm test

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
